DROP TABLE IF EXISTS CURRENCY;

CREATE TABLE CURRENCY (
  ID BIGINT AUTO_INCREMENT  PRIMARY KEY,
  CODE VARCHAR(250),
  CHINESE_NAME VARCHAR(250),
  SYMBOL VARCHAR(250),
  RATE NUMERIC(100000,3),
  DESCRIPTION VARCHAR(250),
  UPDATE_TIME TIMESTAMP
);